services:
  - type: web
    name: blog-sualba
    env: python
    plan: free
    branch: main
    buildCommand: ./render_build.sh
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-sualba-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11
