# Generated by Django 5.2 on 2025-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('web', 'Desarrollo Web'), ('ai', 'IA y ChatGPT'), ('css', 'HTML / CSS'), ('js', 'JavaScript & Frameworks'), ('startup', 'Startups'), ('cyber', 'Cyberseguridad'), ('code', 'El lado Coder - Código de Vida')], default='web', max_length=20),
        ),
    ]
