# Generated by Django 5.2 on 2025-04-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('backend', 'Backend'), ('docker', 'Docker'), ('terminal', 'Terminal y GitHub'), ('chatgpt', 'ChatGPT'), ('ia', 'Inteligencia Artificial'), ('python', 'Python'), ('cyber', 'Cyberseguridad'), ('startup', 'StartUps'), ('excel', 'Excel'), ('salesforce', 'Salesforce'), ('code', 'El lado Coder - Código de vida')], default='html', max_length=20),
        ),
    ]
