# Generated by Django 5.2 on 2025-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(blank=True, help_text='Tu email (opcional)', max_length=254),
        ),
    ]
