# Generated by Django 5.2 on 2025-05-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mensaje_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='suscribir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
