# Generated by Django 5.2 on 2025-05-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_mensaje_suscribir_alter_mensaje_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='suscribir',
        ),
        migrations.AddField(
            model_name='post',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
