# Generated by Django 5.2 on 2026-08-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('cyber', 'Ciberseguridad'), ('osint', 'OSINT'), ('pentesting', 'Pentesting'), ('red-team', 'Red Team'), ('blue-team', 'Blue Team'), ('defensa', 'Defensa y Detección'), ('iso27001', 'ISO 27001'), ('ens', 'ENS (Esquema Nacional de Seguridad)'), ('nist', 'NIST CSF'), ('auditoria', 'Auditoría de Sistemas y Análisis de Riesgos'), ('grc', 'GRC y Cumplimiento'), ('riesgos', 'Gestión de Riesgos'), ('privacidad', 'Privacidad por Diseño y Cumplimiento RGPD'), ('forense', 'Forense / DFIR'), ('web', 'Seguridad Web'), ('python', 'Python: Automatización y Scripting de Seguridad'), ('desarrollo', 'Desarrollo'), ('ia', 'IA y Ciberseguridad'), ('laboratorio', 'Laboratorios'), ('auditsym', 'AuditSym'), ('devops', 'Docker y Despliegue Seguro (Render, Cloud)'), ('redes', 'Redes y Hardening de Sistemas'), ('code', 'El lado Coder - Código de Vida')], default='cyber', max_length=20),
        ),
    ]
