# Generated by Django 5.2 on 2026-08-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='motivo',
            field=models.CharField(choices=[('Auditoría / GRC', 'Auditoría / GRC'), ('AuditSym', 'AuditSym'), ('Colaboración', 'Colaboración'), ('Proyecto tecnológico', 'Proyecto tecnológico'), ('Formación / divulgación', 'Formación / divulgación'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
