# Generated by Django 5.2 on 2026-08-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_mensaje_email_mensaje_motivo_alter_mensaje_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
