# Generated by Django 5.2 on 2026-08-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre o alias')),
                ('email', models.EmailField(help_text='No se mostrará públicamente.', max_length=254, verbose_name='Correo electrónico')),
                ('contenido', models.TextField(max_length=1500, verbose_name='Tu opinión')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('autoriza_mencion', models.BooleanField(default=False, help_text='Permite mencionar esta aportación en una futura publicación. El correo electrónico nunca se publicará.', verbose_name='Autorizo que se mencione mi nombre o alias')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.post')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['fecha'],
            },
        ),
    ]
